"""Add calendar_token to users

Revision ID: c82d4c9ce2d5
Revises: b741dd3b02c6
Create Date: 2026-02-15 13:42:23.880068

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c82d4c9ce2d5"
down_revision = "b741dd3b02c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("calendar_token", sa.String(length=64), nullable=True)
        )
        batch_op.create_unique_constraint(None, ["calendar_token"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("calendar_token")

    # ### end Alembic commands ###
